import { writeFileSync, mkdirSync, copyFileSync } from 'fs'
import { join, dirname } from 'path'
import yaml from 'js-yaml'
import type { ExtractResult } from './extract.js'
import type { PnpmExtractResult } from './extract-pnpm.js'
import type { YarnExtractResult } from './extract-yarn.js'

export type AnyExtractResult = ExtractResult | PnpmExtractResult | YarnExtractResult

export function writeOutput(outputDir: string, result: AnyExtractResult): void {
  mkdirSync(outputDir, { recursive: true })

  writeFileSync(
    join(outputDir, 'package.json'),
    JSON.stringify(result.packageJson, null, 2) + '\n',
  )

  if (result.type === 'npm') {
    writeFileSync(
      join(outputDir, 'package-lock.json'),
      JSON.stringify(result.lockfileJson, null, 2) + '\n',
    )
  } else if (result.type === 'pnpm') {
    const yamlDumpOptions = {
      lineWidth: -1,
      noCompatMode: true,
      quotingType: "'",
      forceQuotes: false,
    } as const
    writeFileSync(
      join(outputDir, 'pnpm-lock.yaml'),
      yaml.dump(result.lockfileYaml, yamlDumpOptions),
    )
    if (Object.keys(result.workspaceYaml).length > 0) {
      writeFileSync(
        join(outputDir, 'pnpm-workspace.yaml'),
        '# Generated by lockfile-subset. Mirrors the pnpm settings recorded in the\n' +
          '# subset pnpm-lock.yaml so `pnpm install --frozen-lockfile` accepts it as-is.\n' +
          yaml.dump(result.workspaceYaml, yamlDumpOptions),
      )
    }
    for (const patch of result.patchFiles) {
      const dest = join(outputDir, patch.relativePath)
      mkdirSync(dirname(dest), { recursive: true })
      copyFileSync(patch.source, dest)
    }
  } else {
    writeFileSync(join(outputDir, 'yarn.lock'), result.lockfileContent)
  }
}
